// Cars Seed Data for UK - Based on Europcar prices + 5% markup

const carsData = [
  // ============ ECONOMY CARS ============
  {
    carName: "Volkswagen Polo",
    brand: "Volkswagen",
    type: "Economy",
    seats: 5,
    doors: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 2,
    pricePerDay: 22,
    image: "/cars/vw-polo.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "Ford Fiesta",
    brand: "Ford",
    type: "Economy",
    seats: 5,
    doors: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 2,
    pricePerDay: 24,
    image: "/cars/ford-fiesta.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning"],
    location: "London Gatwick",
    available: true
  },
  {
    carName: "Vauxhall Corsa",
    brand: "Vauxhall",
    type: "Economy",
    seats: 5,
    doors: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 2,
    pricePerDay: 21,
    image: "/cars/vauxhall-corsa.jpg",
    features: ["Bluetooth", "Air Conditioning", "Central Locking"],
    location: "Manchester Airport",
    available: true
  },
  {
    carName: "Renault Clio",
    brand: "Renault",
    type: "Economy",
    seats: 5,
    doors: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 2,
    pricePerDay: 23,
    image: "/cars/renault-clio.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning"],
    location: "Birmingham Airport",
    available: true
  },

  // ============ COMPACT/SEDAN ============
  {
    carName: "Volkswagen Golf",
    brand: "Volkswagen",
    type: "Sedan",
    seats: 5,
    doors: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 32,
    image: "/cars/vw-golf.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "Ford Focus",
    brand: "Ford",
    type: "Sedan",
    seats: 5,
    doors: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 30,
    image: "/cars/ford-focus.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Parking Sensors"],
    location: "Edinburgh Airport",
    available: true
  },
  {
    carName: "Audi A3",
    brand: "Audi",
    type: "Sedan",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 42,
    image: "/cars/audi-a3.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav"],
    location: "London Gatwick",
    available: true
  },
  {
    carName: "BMW 1 Series",
    brand: "BMW",
    type: "Sedan",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 45,
    image: "/cars/bmw-1-series.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Leather Seats"],
    location: "Manchester Airport",
    available: true
  },

  // ============ SUV ============
  {
    carName: "Nissan Qashqai",
    brand: "Nissan",
    type: "SUV",
    seats: 5,
    doors: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 45,
    image: "/cars/nissan-qashqai.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "Kia Sportage",
    brand: "Kia",
    type: "SUV",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 48,
    image: "/cars/kia-sportage.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Heated Seats"],
    location: "Birmingham Airport",
    available: true
  },
  {
    carName: "Volkswagen Tiguan",
    brand: "Volkswagen",
    type: "SUV",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 55,
    image: "/cars/vw-tiguan.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats"],
    location: "London Gatwick",
    available: true
  },
  {
    carName: "BMW X1",
    brand: "BMW",
    type: "SUV",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 68,
    image: "/cars/bmw-x1.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats"],
    location: "Edinburgh Airport",
    available: true
  },
  {
    carName: "Range Rover Evoque",
    brand: "Land Rover",
    type: "SUV",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 95,
    image: "/cars/range-rover-evoque.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats", "Panoramic Roof"],
    location: "London Heathrow",
    available: true
  },

  // ============ LUXURY ============
  {
    carName: "Mercedes C-Class",
    brand: "Mercedes",
    type: "Luxury",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 75,
    image: "/cars/mercedes-c-class.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "BMW 3 Series",
    brand: "BMW",
    type: "Luxury",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 78,
    image: "/cars/bmw-3-series.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats"],
    location: "London Gatwick",
    available: true
  },
  {
    carName: "Audi A4",
    brand: "Audi",
    type: "Luxury",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 76,
    image: "/cars/audi-a4.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats"],
    location: "Manchester Airport",
    available: true
  },
  {
    carName: "Mercedes E-Class",
    brand: "Mercedes",
    type: "Luxury",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 110,
    image: "/cars/mercedes-e-class.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats", "Massage Seats"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "BMW 5 Series",
    brand: "BMW",
    type: "Luxury",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 115,
    image: "/cars/bmw-5-series.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "Heated Seats", "Sunroof"],
    location: "Birmingham Airport",
    available: true
  },

  // ============ VAN ============
  {
    carName: "Ford Galaxy",
    brand: "Ford",
    type: "Van",
    seats: 7,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 5,
    pricePerDay: 65,
    image: "/cars/ford-galaxy.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "7 Seats"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "Volkswagen Sharan",
    brand: "Volkswagen",
    type: "Van",
    seats: 7,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 5,
    pricePerDay: 68,
    image: "/cars/vw-sharan.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Sliding Doors", "7 Seats"],
    location: "Manchester Airport",
    available: true
  },
  {
    carName: "Mercedes V-Class",
    brand: "Mercedes",
    type: "Van",
    seats: 7,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    airConditioning: true,
    luggage: 6,
    pricePerDay: 125,
    image: "/cars/mercedes-v-class.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Cruise Control", "Sat Nav", "Parking Sensors", "Leather Seats", "7 Seats", "Premium Interior"],
    location: "London Heathrow",
    available: true
  },

  // ============ ELECTRIC ============
  {
    carName: "Tesla Model 3",
    brand: "Tesla",
    type: "Sedan",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 85,
    image: "/cars/tesla-model-3.jpg",
    features: ["Autopilot", "Large Touchscreen", "Air Conditioning", "Supercharger Access", "Premium Sound"],
    location: "London Heathrow",
    available: true
  },
  {
    carName: "Volkswagen ID.4",
    brand: "Volkswagen",
    type: "SUV",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Electric",
    airConditioning: true,
    luggage: 4,
    pricePerDay: 72,
    image: "/cars/vw-id4.jpg",
    features: ["Bluetooth", "Large Touchscreen", "Air Conditioning", "Fast Charging", "Parking Sensors"],
    location: "London Gatwick",
    available: true
  },
  {
    carName: "Nissan Leaf",
    brand: "Nissan",
    type: "Economy",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuelType: "Electric",
    airConditioning: true,
    luggage: 3,
    pricePerDay: 52,
    image: "/cars/nissan-leaf.jpg",
    features: ["Bluetooth", "USB Port", "Air Conditioning", "Fast Charging", "E-Pedal"],
    location: "Edinburgh Airport",
    available: true
  }
];

// UK Locations Data
const ukLocations = [
  { name: "London Heathrow", code: "LHR", type: "Airport", city: "London" },
  { name: "London Gatwick", code: "LGW", type: "Airport", city: "London" },
  { name: "Manchester Airport", code: "MAN", type: "Airport", city: "Manchester" },
  { name: "Birmingham Airport", code: "BHX", type: "Airport", city: "Birmingham" },
  { name: "Edinburgh Airport", code: "EDI", type: "Airport", city: "Edinburgh" },
  { name: "Glasgow Airport", code: "GLA", type: "Airport", city: "Glasgow" },
  { name: "Bristol Airport", code: "BRS", type: "Airport", city: "Bristol" },
  { name: "Liverpool John Lennon", code: "LPL", type: "Airport", city: "Liverpool" },
  { name: "Newcastle Airport", code: "NCL", type: "Airport", city: "Newcastle" },
  { name: "Leeds Bradford", code: "LBA", type: "Airport", city: "Leeds" }
];

module.exports = { carsData, ukLocations };